name: taccari_ext_env
channels:
  - conda-forge
  - pytorch          # for torch, torchvision, torchaudio
dependencies:
  # 1) Core conda packages
  - python=3.10
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib       # or matplotlib-base
  - pytorch=1.11.*   # pulls torch+cpu or torch+cu113 from pytorch channel
  - torchvision=0.12.*  # match your torch build
  - torchaudio=0.11.*
  - torch-scatter
  - torch-sparse
  - torch-cluster
  - torch-spline-conv
  - torch-geometric# match your torch build
  - pip               # make sure pip is available

  # 2) Everything else via pip
  - pip:
    - aiohttp==3.9.3
    - xyzservices==2023.10.1
    - websockets==12.0
    - watchfiles==0.21.0
    - virtualenv==20.25.0
    - torch-geometric-temporal==0.54.0
    - tensorboardx==2.6.2.2
    - starlette==0.32.0.post1
    - smart-open==6.4.0
    - slicer==0.0.7
    - shap==0.44.0
    - rsa==4.9
    - ray==2.9.2
    - qtawesome==1.2.2
    - qstylizer==0.2.2
    - python-dotenv==1.0.1
    - pyproj==3.6.1
    - pylint-venv==2.3.0
    - pydantic-core==2.16.2
    - pydantic==2.6.1
    - pyasn1-modules==0.3.0
    - pyasn1==0.5.1
    - pyarrow==6.0.1
    - py-spy==0.3.14
    - protobuf==4.25.2
    - opencensus-context==0.1.3
    - opencensus==0.11.4
    - nvidia-ml-py==12.535.133
    - numba==0.58.1
    - networkx==3.2.1
    - multidict==6.0.5
    - msgpack==1.0.7
    - llvmlite==0.41.1
    - jinxed==1.2.1
    - httptools==0.6.1
    - h11==0.14.0
    - grpcio==1.60.1
    - gpustat==1.1.1
    - googleapis-common-protos==1.62.0
    - google-auth==2.27.0
    - google-api-core==2.17.1
    - fsspec==2024.2.0
    - frozenlist==1.4.1
    - folium==0.15.1
    - filelock==3.13.1
    - fastapi==0.108.0
    - distlib==0.3.8
    - decorator==4.4.2
    - cython==3.0.6
    - colorful==0.5.6
    - cloudpickle==3.0.0
    - cachetools==5.3.2
    - branca==0.7.0
    - blessed==1.20.0
    - async-timeout==4.0.3
    - annotated-types==0.6.0
    - aiosignal==1.3.1
    - aiorwlock==1.4.0
    - aiohttp-cors==0.7.0
